[project]
name = "TeleBotAPI"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "langchain-openai>=0.3.33",
    "pillow>=11.3.0",
    "pytelegrambotapi>=4.29.1",
    "python-dotenv>=1.1.1",
]
